name: Weather
on:
  push:
    branches:
      - main
jobs:
  weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - env:
          CITY: "New York"
        name: Display Weather
        run: curl wttr.in/${{ env.CITY }}
