name: Weather

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CITY: "New York" # Replace with your desired city

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y perl
        
    - name: Display Weather
      run: |
        perl -e '
          use LWP::Simple;
          my $weather = get("http://wttr.in/$ENV{CITY}?m");
          print $weather;
        ' 2>/dev/null
