name: Weather Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CITY: "New York" # Replace with your desired city

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Display Weather
      run: curl wttr.in/${{ env.CITY }}
