name: Weather Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CITY: "New York" # Replace with your desired city

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Display Weather
      run: |
        import requests
        from bs4 import BeautifulSoup

        city = "${{ env.CITY }}"
        url = f"https://wttr.in/{city}"
        response = requests.get(url)

        soup = BeautifulSoup(response.text, "html.parser")
        weather_output = soup.pre.get_text()

        print(weather_output)
      shell: python
